### ISSUE TITLE
Customize permit application template for Skeena

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_skeena_2024_permit#1]
Best to just do letter for now till I summarize and provide older examples of how we handle the Provincial janky user interface and DFO pdf application form but reason for memo comes from here https://portalext.nrs.gov.bc.ca/web/client/-/scientific-fish-collection-permit and here https://www.pac.dfo-mpo.gc.ca/fm-gp/licence-permis/scientific-scientifique-eng.html.  We apply to province under my name using the `NewGraphEnvironment` bceid from LastPass

Recently updated this for Peace and used that as template for this repo.  Can always use improvements but should be good start.  Reviewing older repos with `permit` in the title (most recent first) to begin is a good idea to understand context for Skeena, to scope for things that might be missed, get easy copy paste links, see mulitiple ways to get same type result (sometimes perhaps unnecessarily more complex in the past and sometimes with necessary tweaks to do certain things like use an `aggregated_crossings_id` vs a `stream_crossing_id`.) 

Don't forget that exec summary of latest Skeena report now links to all older Skeena reports if trying to find sites.

See if it will build with some minor tweaks.  Things to do that I can think of to get ready for Skeena are.  

- [x] customize repo file names, links and remove kml, zip files, pdfs from repo
- [x] Add DFO in address of letter (we have separate application for them that includes this letter as well - see older letters for examples)
- [x] copy over recent `fiss_species_table.csv` from the skeena to fig directory. Maybe let's do this once https://github.com/NewGraphEnvironment/fish_passage_skeena_2023_reporting/pull/124 is merged so we get the updated table
- [x] make a list of sites to get permits for. As you can see this is just a list of numbers so we should be able to add some before we finalize. To start we want Thompson, Glen Vowell, Helps, Coffin, Alvin, Robin, Lemieux Creek (names in reports and `gnis_name` fields of stream layer in qgis).  Consider using `aggregated_crossings_id` vs `stream_crossing

**Comment by lucy-schick** [comment]
okay i'll get started on this

**Comment by NewGraphEnvironment** [comment]
Additional crossings 

- [x] Sandstone (Zymoetz - 2022?)
- [x] 8547 (zymoetz 2023 - include bit of detail in permit so we know which one - ex. trib to mcdonnel lake with sk point near lake)
- [x] Gramaphone
- [x] Waterfall
- [x] Chicago (2023 phase 1 )
- [x] 198916 (Gershwin Creek )
