### ISSUE TITLE
KISP sites 198217 and 198216 missing in `whse_basemapping.fwa_streams_20k_50k` layer

### ISSUE THREAD

**Issue by lucy-schick** [NewGraphEnvironment/fish_passage_skeena_2024_permit#2]
**Issue:**
When trying to get the watershed codes using this code, https://github.com/lucy-schick/fish_passage_skeena_2024_permit/blob/2024_permit/application_moe.Rmd#L184C1-L215C2, no data is returned for site `198217` (Glen Vowell).

![Screen Shot 2024-08-07 at 11 36 00 AM](https://github.com/user-attachments/assets/8fdc90e0-05a1-4587-9938-7cfab756ce32)

**Things I've tried:**
- Checked to see if this is an issue at other sites in the KISP. Only sites where there is missing data seems to be 198217 and 198216
- I checked to see if the `linear_feature_id_20k` for site 198217 is found in the `whse_basemapping.fwa_streams_20k_50k` layer and it doesn't look like it.
```
check <- fpr_db_query(query = "SELECT *
FROM whse_basemapping.fwa_streams_20k_50k
WHERE linear_feature_id_20k = 82059050")
```
   returns 0 results

**Comment by NewGraphEnvironment** [comment]
due to fwa mapping error documented in the memo.  Can use the upstream channel line from 1:50,000.  Not sure what we did last year but always worth looking there for clues


![image](https://github.com/user-attachments/assets/1734c207-350b-47ff-ba29-b31ed4ad4eaf)

**Comment by NewGraphEnvironment** [comment]
just pushed additional 2023 permit application files to https://github.com/NewGraphEnvironment/fish_passage_skeena_2023_reporting/tree/main/data/permit_submission for reference for this as well

**Comment by lucy-schick** [comment]
> due to fwa mapping error documented in the memo.

Can you point me to this memo?

**Comment by lucy-schick** [comment]
Nevermind I found it. Memo here, https://www.newgraphenvironment.com/fish_passage_skeena_2022_reporting/tributary-to-skeena-river---198216-198217---appendix.html

**Comment by lucy-schick** [comment]
in 2023 we delt with this issue by subbing in the `localcode` when the `watershed_code_50k` (aka the watershed code) was missing, script found here https://github.com/NewGraphEnvironment/fish_passage_skeena_2023_permit/blob/main/application_moe.Rmd#L278C3-L281C45
